### ISSUE TITLE
Defining a metric in ab_test help

### ISSUE THREAD

**Issue by noctivityinc** [andrew/split#283]
Sorry I've been out of this for a while.  Was a method ever implemented to define a metric in the ab_test helper?  I can't use the YAML or config for my experiments as some of the alternatives are pulled from a database.

Thanks.

**Comment by andrew** [comment]
I don't believe so, but you could directly call `Split::Metric.find_or_create` just before you call `ab_test`, otherwise I'd be happy to merge a pr to add that functionality to `ab_test`
