### ISSUE TITLE
Archived experiments

### ISSUE THREAD

**Issue by noctivityinc** [andrew/split#284]
All-

I have successfully (locally) implemented archiving experiments from the dashboard.  It's pretty simple - you click to archive and it's archived in the config for the exp, that's it.  It also reads from the config for an exp so, if for some reason, you want to use the config instead of dashboard to archive an exp you can.  Not sure if thats a good idea or not so let me know but either way I THINK storing the archived project in the project config hash makes sense (im new to Redis, so let me know if you think a has called experiments_archived like the experiments_winner makes more sense)

Question - what exactly happens with archived projects that are still LIVE?  Right now they work the same as any other experiment, with the exception that they are archived.  So the exp doesnt appear on the main dashboard screen although its still "experimenting."  Any thoughts on this?  Any reason not to do this?

Thanks for the feedback.  Once finalized Ill submit a pull request.

**Comment by andrew** [comment]
Thanks for working on this @noctivityinc, I'll check out your branch over the weekend, feel free to open a PR now to make it easier to do inline code review.

**Comment by noctivityinc** [comment]
Hey Andrew-

Definitely take a look but, as mentioned, Im not sure it has any real value since the view is basically the same as “winner selected” or “no winner selected” with the way the implementation was done.   

Let me know your thoughts.  



Joshua Lippiner  
.:t 704.323.5661
.:e jlippiner@noctivity.com (mailto:jlippiner@noctivity.com)

**Comment by andrew** [comment]
@noctivityinc I've taken a look at it, and as you said, there's not really much difference, so I don't think it's worth merging at the moment but thanks for investigating it.
