### ISSUE TITLE
Starting experiments is coupled tightly to Split::Helper

### ISSUE THREAD

**Issue by joshdover** [andrew/split#285]
We have a use case where we need to be able to enroll users who are offline in an experiment, however the process for 1) obtaining the Experiment instance; 2) enrolling a user in an experiment; 3) assigning an alternative to the user; are all tightly coupled to the view helper.

This logic (specifically: parts of `ab_test`, all of `start_trial`, and `finished`) should be extracted out of the Helper module. I plan on moving the majority of that logic into the Trial class, which seems like the most appropriate candidate for handling a specific user's status with an experiment.

These changes will not change the helper API, but will make the helper code quite a bit simpler. This will  allow for better testing of the individual pieces of the process, as well as support the use case that our project (I suspect others as well) needs.

**Comment by andrew** [comment]
That sounds brilliant @joshdover!

I'm really looking forward to seeing this happen, let me know if you need my help with the refactoring.
