### ISSUE TITLE
Forced alternative not persisting

### ISSUE THREAD

**Issue by noctivityinc** [andrew/split#290]
I am using split to test two different form variations.  Im trying to force each one for testing but when the form is submitted its always reverting back to the control.  

How do we get a forced alternative in the querystring to persist?

**Comment by cjackson** [comment]
Two things that could be causing this:

1. When calling `finished`, it's resetting the experiment. You can prevent this by passing `reset: false` on the call to `finished`.
2. In your config, you might want to set `config.store_override = true`

**Comment by noctivityinc** [comment]
Got it!  Thanks.  store_override worked for me.



Joshua Lippiner  
.:t 704.323.5661
.:e jlippiner@noctivity.com (mailto:jlippiner@noctivity.com)
